// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFile(arg1) {
  return window['go']['main']['App']['CreateFile'](arg1);
}

export function GetReports() {
  return window['go']['main']['App']['GetReports']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetThreshold() {
  return window['go']['main']['App']['GetThreshold']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function ReportResult(arg1) {
  return window['go']['main']['App']['ReportResult'](arg1);
}

export function UpdateThreshold(arg1) {
  return window['go']['main']['App']['UpdateThreshold'](arg1);
}
