// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateFile(arg1:string):Promise<string>;

export function GetReports():Promise<Array<main.PreviousReport>>;

export function GetSettings():Promise<main.ApplicationSettings>;

export function GetThreshold():Promise<number>;

export function IsConnected():Promise<boolean>;

export function ReportResult(arg1:number):Promise<string>;

export function UpdateThreshold(arg1:number):Promise<void>;
